export const SET_LOADING = "[SET_LOADING] set a loading";
export const SET_ERROR = "[SET_LOADING] set a error";
export const LOAD_ALL_LABEL = "[LOAD_ALL_LABEL] get all labels";
export const STOP_LOADING = "[STOP_LOADING] stops loading";
export const DISMISS_ERROR = "[SET_LOADING] dismiss error";
export const ADD_NEW_LABEL = "[ADD_NEW_LABEL] add new label";
export const CREATE_SNIPPET_FILE = "[CREATE_SNIPPET_FILE] create a file in folder";
export const ON_LABEL_SELECTED = "[ON_LABEL_SELECTED] on label selected";
export const OPEN_SNIPPET_FILE = "[OPEN_SNIPPET_FILE] open snippet file";